### PR TITLE
ZEN-16395 Graphs do not display thresholds unless threshold name is c…

### PR DESCRIPTION
**Pull request by glujan**
…licked

[Jira](https://jira.zenoss.com/browse/ZEN-16395)

### CODE REVIEW

**Comment by rDr4g0n** [comment]
Changes should not be made to the js files in `central-query/src/main/resources/api/`. Those files are the generated output of the js source located at `central-query/src/main/js/visualization`.  

Also, if you make a change to `line.js`, you probably want to make the same change to `area.js`.

To build the js lib (`visualization.js`), youll need nodejs v6 or greater and npm:
* navigate to `central-query/src/main/js/visualization`
* `npm install` to install js build tool dependencies
* now you can build the visualization library with `gulp`, or you can have it automatically build each time you make a change with `gulp watch`
* if you get errors indicating `gulp` isnt found, try `sudo npm install -g gulp` to install the gulp command line tool

**Comment by glujan** [comment]
Please do not merge this PR while #270 is not merged

**Comment by glujan** [comment]
This PR is updated to reflect @rDr4g0n comments

**Comment by glujan** [comment]
I've missed it on purpose. @ssOlexBaiko has done it in #270 and leftovers are (mostly) from his other PR.

@rDr4g0n , do you want me to include those changes here or is it okay the way it is now?

**Comment by glujan** [comment]
This would be merge together with #270 and #271 using additional feature branch in order to sync work across those three PRs.

**Comment by glujan** [comment]
Merged in #273

**Pull request closed without merging**
