### PR TITLE
Feature/visualization cleanup

### PR DESCRIPTION
**Pull request by ssOlexBaiko**

### CODE REVIEW

**Comment by glujan** [comment]
@ssOlexBaiko FYI: just pushed my commit

**Comment by glujan** [comment]
retest

**Comment by ssOlexBaiko** [comment]
retest this

**Comment by ssOlexBaiko** [comment]
retest this

**Comment by romanbakaleyko** [comment]
retest this

**Comment by romanbakaleyko** [comment]
retest

**Comment by ssOlexBaiko** [comment]
retest this

**Comment by romanbakaleyko** [comment]
retest

**Comment by ssOlexBaiko** [comment]
retest this

**Comment by glujan** [comment]
retest this

**Comment by ssOlexBaiko** [comment]
retest this

**Comment by ssOlexBaiko** [comment]
retest this

**Comment by ssOlexBaiko** [comment]
retest this

**Pull request merged**
